/* Standalone design study. Sample records only; no RIM, Zoom, or Google calls. */
(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const main = $('#main');
  const dialog = $('#dialog');
  const icon = (name, cls = '') => (window.RIM_ICONS[name] || '').replace('<svg ', `<svg class="${cls}" `);
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const storageKey = 'rim-member-design-study-v1';
  let saved = {};
  try { saved = JSON.parse(localStorage.getItem(storageKey) || '{}') || {}; } catch {}
  const initialPrefs = {checklist:{favorite:true,color:'blue',collection:'practice'},notes:{color:'green'},resources:{color:'amber'}};
  const state = {
    day:'ready', route:'home', team:'host', folder:'', query:'', filter:'all', filePage:1, conversationPage:1, conversationQuery:'',
    sort:['name','modified','type'].includes(saved.sort) ? saved.sort : 'name',
    prefs:saved.prefs && typeof saved.prefs === 'object' ? saved.prefs : initialPrefs,
    pins: saved.pins && typeof saved.pins === 'object' ? saved.pins : {checklist:'Alex'},
    profile:{first:'Jesse',last:'Foy',preferred:'Jesse',phone:'',bio:'',...(saved.profile || {})}
  };
  const files = [
    {id:'checklist',name:'Host checklist',kind:'Document',date:'Sep 18',stamp:18,by:'Alex',parent:'',text:'A place for the team’s shared session-opening checklist.'},
    {id:'resources',name:'Getting started',kind:'Folder',date:'Sep 16',stamp:16,by:'Morgan',parent:''},
    {id:'notes',name:'September team notes',kind:'Document',date:'Sep 20',stamp:20,by:'Jordan',parent:'',text:'A place for the team’s notes and next steps.'},
    {id:'schedule',name:'Autumn hosting schedule',kind:'Spreadsheet',date:'Sep 19',stamp:19,by:'Alex',parent:'',text:'The hosting schedule would open here.'},
    {id:'peer-notes',team:'peer',name:'Practice group notes',kind:'Document',date:'Sep 19',stamp:19,by:'Morgan',parent:'',text:'A place for notes from the peer-led practice group.'},
    {id:'welcome',name:'Welcome to the host team',kind:'PDF',date:'Sep 15',stamp:15,by:'Morgan',parent:'resources',text:'A place for a welcome and an introduction to the team.'},
    {id:'zoom',name:'Zoom setup guide',kind:'Document',date:'Sep 17',stamp:17,by:'Jordan',parent:'resources',text:'A place for the team’s Zoom setup instructions.'}
  ];
  const mobileFooter = `<footer class="mobile-community"><a class="text-link" href="#care">${icon('HeartHandshake')}Community care</a><button class="text-link" data-demo="A little help">${icon('CircleHelp')}A little help</button></footer>`;
  function persist(){try{localStorage.setItem(storageKey,JSON.stringify({sort:state.sort,prefs:state.prefs,pins:state.pins,profile:state.profile}));}catch{}}
  function hydrateIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
  function announce(message){const el=$('#status');el.textContent=message;el.hidden=false;clearTimeout(announce.timer);announce.timer=setTimeout(()=>{el.hidden=true;},3800);}
  function closeAccount(){ $('#account-menu').hidden=true;$('#account-toggle').setAttribute('aria-expanded','false'); }
  function modal(title,body,actions=''){
    $('#dialog-content').innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">${esc(title)}</h2><button class="icon-button" aria-label="Close dialog" data-action="close">${icon('X')}</button></div>${body}${actions}`;
    if(!dialog.open)dialog.showModal();
    else $('#dialog-content .icon-button').focus();
  }
  function demo(title){modal(title,`<div class="dialog-copy"><p>This is a design preview with sample content.</p><p>${title==='Join on Zoom'?'In RIM, this button takes you to the session on Zoom. No meeting opens from this preview.':title==='A little help'?'In RIM, this would lead to member support and practical help.':'This destination is outside the first prototype. Your account and the live site have not changed.'}</p></div>`,`<div class="dialog-actions"><button class="secondary" data-action="close">Back to preview</button></div>`);}
  function heading(title,subtitle='',date=''){return `<header class="page-heading">${date?`<p class="date">${date}</p>`:''}<h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</header>`;}
  function setRail(){
    const inHub = ['team','files','conversations','members'].includes(state.route);
    $('#rail-main').innerHTML=inHub?`<a class="back-teams" href="#teams">${icon('ArrowLeft')}My Teams</a><div class="team-rail-title">${state.team==='peer'?'Peer-led practice':'Host team'}</div><nav class="hub-nav" aria-label="Team navigation">${[['team','House','Home'],['conversations','MessageCircle','Conversations'],['files','Folder','Files'],['members','UsersRound','Members']].map(([r,i,t])=>`<a href="#${r}" ${state.route===r?'aria-current="page"':''}>${icon(i)}${t}</a>`).join('')}</nav>`:`<p class="rail-heading">My RIM</p><nav aria-label="Personal navigation">${[['home','House','My Home'],['library','BookOpen','Library'],['teams','UsersRound','My Teams']].map(([r,i,t])=>`<a href="#${r}" ${state.route===r?'aria-current="page"':''}>${icon(i)}${t}</a>`).join('')}</nav>`;
    document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===state.route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
    $('.manage-link').setAttribute('aria-label','Manage RIM');
    if(state.route==='manage')$('.manage-link').setAttribute('aria-current','page');else $('.manage-link').removeAttribute('aria-current');
  }
  function home(){
    const ready=state.day==='ready';
    const today=state.day==='empty'
      ? `<div class="empty-state"><h3>No sessions today.</h3><p>Our next gatherings are on the weekly schedule.</p><a class="secondary" href="#schedule">See the schedule ${icon('ArrowRight')}</a></div>`
      : `<div class="today-surface"><article class="session-main"><div class="session-time">9:00 AM<span>Central time</span></div><div class="session-details"><h3>Good Morning Sangha</h3><p class="session-meta">Online on Zoom</p><div class="session-action">${ready?`<button class="primary" data-demo="Join on Zoom">${icon('Video')}Join on Zoom ${icon('ArrowUpRight')}</button>`:`<p class="row-meta">The room opens at 8:50 AM.</p>`}</div><details class="preparation"><summary>Good to know</summary><p>There will be a few quiet minutes before we begin. You’re welcome to arrive early and settle in.</p></details></div></article><div class="later-section"><div class="later-row"><time>7:00 PM</time><div><h3>Evening Meditation</h3><p>Online on Zoom · Room opens at 6:50&nbsp;PM</p></div></div></div></div>`;
    return `${heading(`Good morning, ${esc(state.profile.preferred || state.profile.first)}.`, '', 'Monday, September 21')}<section aria-labelledby="today-title"><div class="section-heading"><h2 id="today-title">Today at RIM</h2></div>${today}</section><nav class="home-next" aria-label="More programs"><a class="text-link" href="#upcoming">Your upcoming programs ${icon('ArrowRight')}</a>${state.day==='empty'?'':`<a class="text-link" href="#schedule">Full schedule ${icon('ArrowRight')}</a>`}</nav>`;
  }
  function upcoming(){return `${heading('Your upcoming programs','All times Central')}<a class="upcoming-row" href="#program"><span class="date-block"><span>Sep</span><strong>23</strong></span><span><span class="row-title">Foundations of Mindfulness</span><span class="row-meta">Wednesday · 6:30 PM · In person</span></span>${icon('ChevronRight')}</a><a class="upcoming-row" href="#program"><span class="date-block"><span>Sep</span><strong>26</strong></span><span><span class="row-title">Saturday Morning Practice</span><span class="row-meta">Saturday · 9:00 AM · Online</span></span>${icon('ChevronRight')}</a><a href="#home" class="text-link section-spacer">${icon('ArrowLeft')}Back to My Home</a>`;}
  function teams(){return `${heading('My Teams','The people you practice and serve with.')}<div class="directory"><a href="#team" data-team="host" class="directory-row"><span class="team-symbol">${icon('UsersRound')}</span><div><h2>Host team</h2><p>Welcoming people and supporting our shared practice.</p></div>${icon('ChevronRight')}</a><a href="#team" data-team="peer" class="directory-row"><span class="team-symbol">${icon('Leaf')}</span><div><h2>Peer-led practice</h2><p>Holding a space for silent meditation together.</p></div>${icon('ChevronRight')}</a></div>`;}
  function team(){
    const teamName=state.team==='peer'?'Peer-led practice':'Host team';
    const destinations=[['conversations','MessageCircle','Conversations','Read and write to the team.'],['files','Folder','Files','Find shared documents and folders.'],['members','UsersRound','Members','See who’s on the team.']];
    return `${heading(teamName,state.team==='peer'?'Holding a space for silent meditation together.':'Welcoming people and supporting our shared practice.')}<nav class="team-destinations" aria-label="Team destinations">${state.team==='host'?`<button class="destination-row" data-demo="Hosting schedule"><span class="destination-icon">${icon('CalendarDays')}</span><span><span class="destination-title">Hosting schedule</span><span class="destination-description">See when you’re hosting.</span></span>${icon('ChevronRight')}</button>`:''}${destinations.map(([route,i,title,description])=>`<a class="destination-row" href="#${route}"><span class="destination-icon">${icon(i)}</span><span><span class="destination-title">${title}</span><span class="destination-description">${description}</span></span>${icon('ChevronRight')}</a>`).join('')}</nav>`;
  }
  function profile(){const p=state.profile;return `${heading('My Profile')}<div class="profile-intro"><span class="avatar">${esc((p.first||'J')[0])}</span><div><h2>${esc(p.first)} ${esc(p.last)}</h2><p>Your profile and contact details</p></div></div><div class="profile-grid"><div class="profile-surface"><section class="profile-section"><div class="section-heading"><h2>About me</h2><button class="text-link" data-action="edit-bio">Edit</button></div><p>${p.bio?esc(p.bio):'You haven’t added a bio yet.'}</p></section><section class="profile-section"><div class="section-heading"><h2>Personal details</h2><button class="text-link" data-action="edit-profile">Edit</button></div><dl class="details-list"><div><dt>Name</dt><dd>${esc(p.first)} ${esc(p.last)}</dd></div><div><dt>Preferred name</dt><dd>${esc(p.preferred)||'Not added'}</dd></div><div><dt>Phone</dt><dd>${esc(p.phone)||'Not added'}</dd></div></dl></section><section class="profile-section"><div class="section-heading"><h2>Profile photo</h2></div><p>You can use a photo or keep your initial.</p><button class="text-link" data-demo="Choose a profile photo">Choose a photo ${icon('ArrowRight')}</button></section></div><aside class="account-notes"><section><h2>Signing in</h2><p>Sign-in codes go to your email address.</p><p>jesse@example.org</p><button class="text-link" data-demo="Change your email">Need to change your email? ${icon('ArrowRight')}</button></section><section class="section-spacer"><h2>Household</h2><p>Manage the people connected to your household.</p><button class="text-link" data-demo="Your household">View household ${icon('ArrowRight')}</button></section></aside></div>`;}
  function editProfile(){const p=state.profile;modal('Personal details',`<form id="profile-form"><div class="form-grid"><label class="field">First name<input name="first" autocomplete="given-name" value="${esc(p.first)}" required></label><label class="field">Last name<input name="last" autocomplete="family-name" value="${esc(p.last)}" required></label><label class="field field-full">Preferred name<input name="preferred" autocomplete="nickname" value="${esc(p.preferred)}"></label><label class="field field-full">Phone <span class="row-meta">Optional</span><input name="phone" type="tel" autocomplete="tel" value="${esc(p.phone)}"></label></div><div class="dialog-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary" type="submit">Save changes</button></div></form>`);}
  function editBio(){modal('About me',`<form id="bio-form"><label class="field">A little about you<textarea name="bio" placeholder="A few words about your practice or your connection to RIM.">${esc(state.profile.bio)}</textarea></label><div class="dialog-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary" type="submit">Save changes</button></div></form>`);}
  function filePage(){return `<header class="files-heading"><p class="eyebrow">${state.team==='peer'?'Peer-led practice':'Host team'}</p><h1>Files</h1><p class="personal-note">${icon('UserRound')}<span>Your colors, favorites, and collections are just for you. Team pins are shared.</span></p></header><div class="file-controls"><label class="search-field"><span>Find a file</span>${icon('Search')}<input type="search" id="file-search" placeholder="Search this team’s files" value="${esc(state.query)}"></label><label class="sort-field"><span>Sort for me</span><select id="file-sort"><option value="name" ${state.sort==='name'?'selected':''}>Name, A–Z</option><option value="modified" ${state.sort==='modified'?'selected':''}>Recently updated</option><option value="type" ${state.sort==='type'?'selected':''}>File type</option></select></label></div><div class="file-tabs" aria-label="Personal file views">${[['all','All files'],['favorites','My favorites'],['practice','My collection: Weekly practice']].map(([v,t])=>`<button aria-pressed="${state.filter===v}" data-filter="${v}">${t}</button>`).join('')}</div><div id="file-results" tabindex="-1"></div>`;}
  function visibleFiles(){let list=files.filter(f=>(f.team||'host')===state.team).filter(f=>state.query ? f.name.toLowerCase().includes(state.query.toLowerCase()) : state.filter==='all'?f.parent===state.folder:true);if(state.filter==='favorites')list=list.filter(f=>state.prefs[f.id]?.favorite);if(state.filter==='practice')list=list.filter(f=>state.prefs[f.id]?.collection==='practice');return list.sort((a,b)=>{if(state.sort==='modified')return b.stamp-a.stamp;if(state.sort==='type')return a.kind.localeCompare(b.kind)||a.name.localeCompare(b.name);return Number(b.kind==='Folder')-Number(a.kind==='Folder')||a.name.localeCompare(b.name);});}
  const colorChoices=[['Blue','#31576d'],['Green','#2e7d32'],['Gold','#b98730'],['Plum','#865d87'],['Coral','#ba6654']];
  function colorValue(value){
    const legacy={blue:'#31576d',green:'#2e7d32',amber:'#7a4f00'};
    if(legacy[value])return legacy[value];
    return typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)?value.toLowerCase():'';
  }
  function colorName(value){const color=colorValue(value);return colorChoices.find(([,hex])=>hex===color)?.[0]||(color?'Custom color':'No color');}
  function fileRow(f,pinned){
    const pref=state.prefs[f.id]||{},color=colorValue(pref.color);
    return `<div class="file-row"><button class="file-open" data-open-file="${f.id}"><span class="file-kind ${color?'file-kind-colored':''}" ${color?`style="--file-color:${color}"`:''}>${icon(f.kind==='Folder'?'Folder':'FileText')}</span><span><strong>${esc(f.name)} ${pref.favorite?icon('Star','favorite-mark'):''}</strong><small>${pinned?`Pinned for the team by ${esc(state.pins[f.id])}`:esc(f.kind)}${color?` · ${colorName(color)}`:''}${pref.collection==='practice'?' · Weekly practice':''}</small></span></button><span class="file-date">Updated ${f.date}</span><button class="icon-button" data-file-options="${f.id}" aria-label="Options for ${esc(f.name)}">${icon('MoreHorizontal')}</button></div>`;
  }
  function renderFiles(){const all=visibleFiles();const ordered=[...all.filter(f=>state.pins[f.id]),...all.filter(f=>!state.pins[f.id])];const pages=Math.max(1,Math.ceil(ordered.length/8));state.filePage=Math.min(state.filePage,pages);const list=ordered.slice((state.filePage-1)*8,state.filePage*8);const pinned=list.filter(f=>state.pins[f.id]);const others=list.filter(f=>!state.pins[f.id]);const breadcrumb=state.folder&&!state.query&&state.filter==='all'?`<nav class="file-breadcrumb" aria-label="Folder path"><button data-action="folder-root">Files</button>${icon('ChevronRight')}<span>Getting started</span></nav>`:'';$('#file-results').innerHTML=`${breadcrumb}${pinned.length?`<section class="file-section"><h2 class="file-section-title">${icon('Pin')}Pinned for the team</h2><div class="files-surface">${pinned.map(f=>fileRow(f,true)).join('')}</div></section>`:''}${others.length?`<section class="file-section"><h2 class="file-section-title">${state.filter==='all'?'Files and folders':state.filter==='favorites'?'My favorites':'Weekly practice'}</h2><div class="files-surface">${others.map(f=>fileRow(f,false)).join('')}</div></section>`:''}${!list.length?`<div class="empty-state"><h2>No files here yet.</h2><p>${state.query?'Try another name.':state.filter==='favorites'?'Open a file’s options to add it to your favorites.':'Open a file’s options to add it to this collection.'}</p><button class="secondary" data-action="reset-files">Show all files</button></div>`:''}<p class="file-count" role="status">${all.length} ${all.length===1?'item':'items'}${state.query?' found':''}</p>${pagination(state.filePage,pages,'files')}`;}
  function fileOptions(id){
    const f=files.find(f=>f.id===id),p=state.prefs[id]||{},color=colorValue(p.color);
    modal(f.name,`<form id="file-preferences" data-id="${id}"><div class="preferences"><fieldset class="color-field"><legend>My file color</legend><p class="row-meta">Only you see this color.</p><input type="hidden" name="color" value="${color}"><div class="color-choices">${colorChoices.map(([name,hex])=>`<button type="button" class="color-choice" data-color-choice="${hex}" aria-label="${name}" aria-pressed="${color===hex}"><span style="background:${hex}" aria-hidden="true"></span></button>`).join('')}<button class="text-link" type="button" data-color-choice="" aria-pressed="${!color}">No color</button></div><label class="custom-color"><input id="custom-file-color" type="color" value="${color||'#31576d'}"><span>Choose any color</span></label><p id="color-selection" class="row-meta" role="status">${colorName(color)} selected</p></fieldset><label class="check-field"><input type="checkbox" name="favorite" ${p.favorite?'checked':''}><span>Add to my favorites</span></label><details class="more-preferences"><summary>My collection</summary><label class="field">Add a personal shortcut<select name="collection"><option value="" ${!p.collection?'selected':''}>No collection</option><option value="practice" ${p.collection==='practice'?'selected':''}>Weekly practice</option></select><span class="row-meta">The shared file stays where it is.</span></label></details><div class="shared-setting"><label class="check-field"><input type="checkbox" name="pin" ${state.pins[id]?'checked':''}><span>Pin for the team<small>Visible to everyone in this team. Any member with editing access can change team pins.</small></span></label></div></div><div class="dialog-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary" type="submit">Save preferences</button></div></form>`);
  }
  function selectFileColor(value){
    const color=colorValue(value),form=$('#file-preferences');if(!form)return;
    $('[name="color"]',form).value=color;
    if(color)$('#custom-file-color').value=color;
    form.querySelectorAll('[data-color-choice]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.colorChoice===color)));
    $('#color-selection').textContent=colorName(color)+' selected';
  }
  function openFile(id){const f=files.find(f=>f.id===id);if(f.kind==='Folder'){state.folder=id;state.filter='all';state.query='';state.filePage=1;render();return;}modal(f.name,`<div class="dialog-copy"><p>${esc(f.text)}</p><p>This preview uses sample files. No shared document is opened or changed.</p></div>`,`<div class="dialog-actions"><button class="secondary" data-action="close">Back to files</button><button class="primary" data-file-options="${id}">My file preferences</button></div>`);}
  function library(){return `${heading('Library','Return to the teachings and courses you’re spending time with.')}<div class="directory"><div class="library-row"><span class="team-symbol">${icon('BookOpen')}</span><div><h2>Foundations of Mindfulness</h2><p>Course materials · Your enrolled course</p></div><button class="quiet" data-demo="Foundations of Mindfulness">Open course ${icon('ArrowRight')}</button></div><div class="library-row"><span class="team-symbol">${icon('Headphones')}</span><div><h2>A guided sitting practice</h2><p>Audio · 20 minutes</p></div><button class="quiet" data-demo="A guided sitting practice">Listen ${icon('ArrowRight')}</button></div></div>`;}
  function care(){return `${heading('Community care')}<div class="reading"><p class="lead">These four intentions are all we ask of members. They are directions to hold, not requirements to be graded on. We return to them as a practice: honestly, and with room to begin again.</p><ol class="agreements">${[
    ['Care for Yourself','We care for the conditions that help us see clearly and take responsibility for our own path. Teachers and community offer support, and the walking is ours to do.'],
    ['Care for Others','We care for one another through our presence, speech, and actions. Guided by goodwill, we listen deeply, speak truthfully and kindly, and seek not to cause harm.'],
    ['Care for RIM','RIM is held through dana, the practice of mutual generosity. Financial support meets the center’s practical needs and keeps the teachings freely offered. Time, care, and sincere presence in practice and learning nourish the life of the sangha. We trust each person to discern what is possible; no one is expected to offer in every way, and belonging is never measured by what or how much one gives.'],
    ['Care for Our Shared Vision','We let wisdom and compassion inform our actions, lessening suffering and nurturing well-being in ourselves, one another, those we love, and the world we share.']
  ].map(([t,p])=>`<li><div><h2>${t}</h2><p>${p}</p></div></li>`).join('')}</ol><a class="text-link section-spacer" href="#home">${icon('ArrowLeft')}Back to My Home</a></div>`;}
  function manage(){return `${heading('Manage RIM','Community administration')}<div class="directory">${[['UsersRound','Members','Member records, roles, and team membership'],['House','Households','People connected through a household'],['LayoutGrid','Teams and spaces','Team settings and available tools'],['Mail','Emails','Community email templates'],['Folder','Google Files','File connections and administration']].map(([i,t,p])=>`<a href="#" class="directory-row" data-demo="${t}"><span class="team-symbol">${icon(i)}</span><div><h2>${t}</h2><p>${p}</p></div>${icon('ChevronRight')}</a>`).join('')}</div>`;}
  function schedule(){return `${heading('This week at RIM','A preview of the schedule without member preparation notes.')}<div class="directory">${[['Monday, September 21','Good Morning Sangha','9:00 AM · Online'],['Monday, September 21','Evening Meditation','7:00 PM · Online'],['Wednesday, September 23','Foundations of Mindfulness','6:30 PM · In person']].map(([day,t,time])=>`<a class="directory-row" href="#program"><span class="team-symbol">${icon('CalendarDays')}</span><div><p class="eyebrow">${day}</p><h2>${t}</h2><p>${time}</p></div>${icon('ChevronRight')}</a>`).join('')}</div><a href="#home" class="text-link section-spacer">${icon('ArrowLeft')}Back to My Home</a>`;}
  const conversationSamples=[
    ['gathering','Preparing for our next gathering','Alex','September 20','The updated checklist is in our team files.'],
    ['notes','A few notes from this week','Morgan','September 18','Notes from our last gathering are ready to read.'],
    ['welcome','Welcoming new hosts','Jordan','September 16','A place for introductions and questions from new hosts.'],
    ['autumn','Autumn hosting schedule','Alex','September 14','The autumn schedule is ready in Files.'],
    ['checklist','Our session checklist','Morgan','September 12','A place to discuss the shared session checklist.'],
    ['practice','Supporting quiet practice','Jordan','September 10','A conversation about holding the room for practice.'],
    ['questions','Questions about hosting','Alex','September 8','A place for the team’s practical questions.'],
    ['thanks','Thank you for this month','Morgan','September 6','A note of appreciation for the team.']
  ];
  function pagination(page,pages,kind){return pages>1?`<nav class="pagination" aria-label="${kind==='files'?'File':'Conversation'} pages"><button class="secondary" data-page-kind="${kind}" data-page="${page-1}" ${page===1?'disabled':''}>Previous</button><span>Page ${page} of ${pages}</span><button class="secondary" data-page-kind="${kind}" data-page="${page+1}" ${page===pages?'disabled':''}>Next</button></nav>`:'';}
  function conversations(){return `${heading('Conversations',state.team==='peer'?'Peer-led practice':'Host team')}<div class="file-controls"><label class="search-field"><span>Find a conversation</span>${icon('Search')}<input type="search" id="conversation-search" placeholder="Search by topic" value="${esc(state.conversationQuery)}"></label></div><div id="conversation-results" tabindex="-1"></div>`;}
  function renderConversations(){
    const samples=state.team==='peer'?conversationSamples.slice(0,2):conversationSamples;
    const matches=samples.filter(([,title])=>title.toLowerCase().includes(state.conversationQuery.toLowerCase()));
    const pages=Math.max(1,Math.ceil(matches.length/5));state.conversationPage=Math.min(state.conversationPage,pages);
    const shown=matches.slice((state.conversationPage-1)*5,state.conversationPage*5);
    $('#conversation-results').innerHTML=`<div class="conversation-list">${shown.map(([id,title,by,date])=>`<button class="conversation-row" data-conversation="${id}"><span><span class="row-title">${title}</span><span class="row-meta">${by} · ${date}</span></span>${icon('ChevronRight')}</button>`).join('')||'<p class="file-empty">No conversations match. Try another topic.</p>'}</div><p class="file-count" role="status">${matches.length} conversations</p>${pagination(state.conversationPage,pages,'conversations')}`;
  }
  function members(){return `${heading('Members',state.team==='peer'?'Peer-led practice':'Host team')}<div class="directory">${['Alex','Morgan','Jordan','Jesse'].map(n=>`<div class="directory-row"><span class="avatar">${n[0]}</span><div><h2>${n}</h2><p>Team member</p></div></div>`).join('')}</div>`;}
  function render(focus=false){
    const pages={home,upcoming,teams,team,profile,files:filePage,library,care,manage,schedule,conversations,members,program:()=>`${heading('Program details')}<div class="empty-state"><h2>A clear way back.</h2><p>Full program details remain on the existing website. This study focuses on the member home and its navigation.</p><a href="#home" class="secondary">${icon('ArrowLeft')}Back to My Home</a></div>`};
    const page=pages[state.route]||home;main.innerHTML=`<div class="content ${['home','team','upcoming'].includes(state.route)?'content-quiet':''}">${page()}${mobileFooter}</div>`;setRail();if(state.route==='files')renderFiles();if(state.route==='conversations')renderConversations();hydrateIcons();closeAccount();$('.account-name').textContent=state.profile.preferred||state.profile.first;$('.account-button .avatar').textContent=(state.profile.first||'J')[0];$('#account-menu p').innerHTML=`${esc(state.profile.first)} ${esc(state.profile.last)}<span>My account</span>`;document.title=`${({home:'My Home',upcoming:'Your upcoming programs',teams:'My Teams',profile:'My Profile',files:'Files',care:'Community care',manage:'Manage RIM'})[state.route]||'My RIM'} · Design study`;if(focus){main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
  }
  $('#day-state').addEventListener('change',e=>{state.day=e.target.value;if(state.route!=='home')location.hash='home';else render();});
  $('#account-toggle').addEventListener('click',()=>{const open=$('#account-menu').hidden;$('#account-menu').hidden=!open;$('#account-toggle').setAttribute('aria-expanded',String(open));});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#account-menu').hidden){closeAccount();$('#account-toggle').focus();}});
  document.addEventListener('click',e=>{
    if(!e.target.closest('.account-wrap'))closeAccount();
    const teamLink=e.target.closest('[data-team]');if(teamLink){state.team=teamLink.dataset.team;state.folder='';state.query='';state.filter='all';state.filePage=1;state.conversationPage=1;state.conversationQuery='';}
    const pageButton=e.target.closest('[data-page-kind]');if(pageButton){if(pageButton.dataset.pageKind==='files'){state.filePage=Number(pageButton.dataset.page);renderFiles();$('#file-results').focus();}else{state.conversationPage=Number(pageButton.dataset.page);renderConversations();$('#conversation-results').focus();}return;}
    const conversation=e.target.closest('[data-conversation]');if(conversation){const item=conversationSamples.find(([id])=>id===conversation.dataset.conversation);modal(item[1],`<div class="dialog-copy"><p class="row-meta">${item[2]} · ${item[3]}</p><p>${item[4]}</p></div>`,`<div class="dialog-actions"><button class="secondary" data-action="close">Back to conversations</button></div>`);return;}
    const demoLink=e.target.closest('[data-demo]');if(demoLink){e.preventDefault();demo(demoLink.dataset.demo);return;}
    const colorChoice=e.target.closest('[data-color-choice]');if(colorChoice){selectFileColor(colorChoice.dataset.colorChoice);return;}
    const option=e.target.closest('[data-file-options]');if(option){fileOptions(option.dataset.fileOptions);return;}
    const open=e.target.closest('[data-open-file]');if(open){openFile(open.dataset.openFile);return;}
    const filter=e.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;state.folder='';state.filePage=1;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===filter)));renderFiles();return;}
    const action=e.target.closest('[data-action]')?.dataset.action;
    if(action==='close')dialog.close();if(action==='edit-profile')editProfile();if(action==='edit-bio')editBio();if(action==='folder-root'){state.folder='';state.filePage=1;renderFiles();}if(action==='reset-files'){state.folder='';state.query='';state.filter='all';state.filePage=1;render();}
  });
  document.addEventListener('input',e=>{if(e.target.id==='conversation-search'){state.conversationQuery=e.target.value;state.conversationPage=1;renderConversations();}if(e.target.id==='custom-file-color')selectFileColor(e.target.value);if(e.target.id==='file-search'){state.query=e.target.value;state.filePage=1;renderFiles();}});
  document.addEventListener('change',e=>{if(e.target.id==='custom-file-color')selectFileColor(e.target.value);if(e.target.id==='file-sort'){state.sort=e.target.value;state.filePage=1;persist();renderFiles();}});
  document.addEventListener('submit',e=>{
    if(!['profile-form','bio-form','file-preferences'].includes(e.target.id))return;e.preventDefault();const data=new FormData(e.target);
    if(e.target.id==='profile-form'){for(const key of ['first','last','preferred','phone'])state.profile[key]=String(data.get(key)||'').trim();}
    if(e.target.id==='bio-form')state.profile.bio=String(data.get('bio')||'').trim();
    if(e.target.id==='file-preferences'){const id=e.target.dataset.id;state.prefs[id]={favorite:data.has('favorite'),color:colorValue(data.get('color')),collection:String(data.get('collection'))};if(data.has('pin'))state.pins[id]=state.pins[id]||'You';else delete state.pins[id];}
    const focusSelector=e.target.id==='file-preferences'?`[data-file-options="${e.target.dataset.id}"]`:e.target.id==='bio-form'?'[data-action="edit-bio"]':'[data-action="edit-profile"]';
    persist();dialog.close();render();$(focusSelector)?.focus();announce('Saved in this preview. The live site is unchanged.');
  });
  window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';if(dialog.open)dialog.close();render(true);});
  state.route=location.hash.slice(1)||'home';render();
})();
